Allow disabling terrascan
SeisoLLC/goat pull request #11
Opened 2021-02-22 21:50 UTC by JonZeolla

# Contributor Comments
Allow disabling `terrascan`

## Pull Request Checklist
Thank you for submitting a contribution to `goat`!

In order to streamline the review of your contribution we ask that you review and comply with the below requirements:
- [X] Rebase your branch against the latest commit of the target branch, which likely should be `main`
- [X] If there is an issue associated with your Pull Request, align your PR title with [this documentation](https://help.github.com/en/articles/closing-issues-using-keywords)

2021-02-24 13:27 UTC, tpears requested changes
Remove `$` from bash code blocks that don't need to differentiate between commands and their output.

2021-02-24 13:27 UTC, tpears commented on README.md
> +$ mkdir -p .github/etc/
7 & 8 break the markdown linter: `Dollar signs used before commands without showing output`

2021-02-24 13:27 UTC, tpears commented on README.md
> +$ mkdir -p .github/linters/
Would expect 54 & 55 to throw the linter error as in 7 & 8 but they were not in the log.

2021-02-24 13:27 UTC, tpears commented on README.md
> +$ mkdir -p .github/linters/
It only throws the error when all lines in a block begin with the `$`. Markdown style guidelines advise against using `$` unless you're using it to distinguish between entered commands and their output.

https://github.com/markdownlint/markdownlint/commit/0ec5e846be70641641aaf670c48dfe7972106e96
\<removed dead link\>

2021-02-24 20:23 UTC, JonZeolla commented
Sorry for that @tpears I got green on d9bfc42 and didn't expect my follow-on commits to cause an issue.  Should be good to go now

2021-02-25 03:40 UTC, tpears approved these changes

2021-02-25 03:40 UTC, merged